<?php
defined('BASEPATH') or exit('No direct script access allowed');

/**
 * Import Controller
 * 
 * Handles CSV import for Deposito data with Excel data anomalies
 * - Excel Serial Date conversion
 * - Float to Integer ID casting
 * - Phone number extraction
 * - Status detection from keterangan
 * 
 * @author Generated by AI
 * @version 1.0
 */
class Import extends CI_Controller
{
    public function __construct()
    {
        parent::__construct();
        $this->load->database();
        $this->load->helper(['url', 'form']);
        $this->load->library(['session', 'upload']);

        // Check authentication
        if (!$this->session->userdata('isLoggedIn')) {
            redirect('auth');
        }

        // Check authorization
        $allowed_roles = ['Admin', 'Direktur'];
        $level = $this->session->userdata('level');
        if (!in_array($level, $allowed_roles)) {
            redirect('unauthorized_403');
        }
    }

    /**
     * Display import form
     */
    public function index()
    {
        $data = [
            'level' => $this->session->userdata('level')
        ];

        $parser = [
            'judul' => '<i class="fa fa-upload"></i> Import Data Deposito dari CSV',
            'isi' => $this->load->view('import/import_view', $data, TRUE)
        ];
        $this->parser->parse('templates/main', $parser);
    }

    /**
     * Handle file upload and import process
     */
    public function upload()
    {
        // Response structure
        $response = [
            'success' => false,
            'message' => '',
            'stats' => [
                'anggota_created' => 0,
                'anggota_found' => 0,
                'deposito_inserted' => 0,
                'deposito_updated' => 0,
                'rows_skipped' => 0,
                'errors' => []
            ]
        ];

        // Check if file uploaded
        if (empty($_FILES['csv_file']['name'])) {
            $response['message'] = 'File tidak ditemukan';
            echo json_encode($response);
            return;
        }

        // Configure upload
        $config['upload_path'] = './uploads/import/';
        $config['allowed_types'] = 'csv';
        $config['max_size'] = 10240; // 10MB
        $config['file_name'] = 'deposito_' . date('YmdHis') . '_' . uniqid();

        // Create directory if not exists
        if (!is_dir($config['upload_path'])) {
            mkdir($config['upload_path'], 0755, true);
        }

        $this->upload->initialize($config);

        if (!$this->upload->do_upload('csv_file')) {
            $response['message'] = $this->upload->display_errors('', '');
            echo json_encode($response);
            return;
        }

        $upload_data = $this->upload->data();
        $file_path = $upload_data['full_path'];

        // Process CSV
        $result = $this->_process_csv($file_path);

        $response['success'] = $result['success'];
        $response['message'] = $result['message'];
        $response['stats'] = $result['stats'];

        echo json_encode($response);
    }

    /**
     * Process CSV file and import data
     * 
     * @param string $file_path Full path to CSV file
     * @return array Result array
     */
    private function _process_csv($file_path)
    {
        $stats = [
            'anggota_created' => 0,
            'anggota_found' => 0,
            'deposito_inserted' => 0,
            'deposito_updated' => 0,
            'rows_skipped' => 0,
            'errors' => []
        ];

        // Open file
        $handle = fopen($file_path, 'r');
        if ($handle === false) {
            return [
                'success' => false,
                'message' => 'Gagal membuka file CSV',
                'stats' => $stats
            ];
        }

        // Start transaction
        $this->db->trans_start();

        $row_num = 0;
        $data_start_row = 4; // Data starts at row 4 (header at row 3)

        while (($row = fgetcsv($handle, 0, ',')) !== false) {
            $row_num++;

            // Skip header rows (rows 1-3)
            if ($row_num < $data_start_row) {
                continue;
            }

            // Skip empty rows
            if (empty($row) || empty(trim($row[1] ?? ''))) {
                $stats['rows_skipped']++;
                continue;
            }

            try {
                $imported = $this->_import_row($row, $row_num, $stats);
                if (!$imported) {
                    $stats['rows_skipped']++;
                }
            } catch (Exception $e) {
                $stats['errors'][] = "Row $row_num: " . $e->getMessage();
                $stats['rows_skipped']++;
            }
        }

        fclose($handle);

        // Complete transaction
        $this->db->trans_complete();

        $success = $this->db->trans_status();

        return [
            'success' => $success,
            'message' => $success
                ? 'Import berhasil! ' . ($stats['deposito_inserted'] + $stats['deposito_updated']) . ' deposito diproses.'
                : 'Import gagal, perubahan dibatalkan.',
            'stats' => $stats
        ];
    }

    /**
     * Import a single row
     * 
     * CSV Column Mapping (0-indexed):
     * 0=NO, 1=NAMA, 2=ALAMAT, 3=NO.SERI, 4=JUMLAH DEPOSITO, 5=TGL DEPOSITO
     * 6=JANGKA WAKTU, 7=JATUH TEMPO, 8=SUKU BUNGA, 9=BUNGA(calc), 10=TELP/KET, 11=KET
     * 
     * @param array $row CSV row data
     * @param int $row_num Row number for error reporting
     * @param array &$stats Statistics array (passed by reference)
     * @return bool Success status
     */
    private function _import_row($row, $row_num, &$stats)
    {
        // Extract data from row
        $nama = trim($row[1] ?? '');
        if (empty($nama)) {
            return false;
        }

        $alamat = trim($row[2] ?? '-');
        $no_seri = $this->_parse_int($row[3] ?? 0);
        $jumlah_deposito = $this->_parse_amount($row[4] ?? 0);
        $tgl_deposito = $this->_excel_date_to_php($row[5] ?? '');
        $jangka_waktu = $this->_parse_int($row[6] ?? 12) ?: 12;
        $tgl_jatuh_tempo = $this->_excel_date_to_php($row[7] ?? '');
        $persentase_bunga = $this->_parse_rate($row[8] ?? 0);
        $phone_or_ket = trim($row[10] ?? '');
        $keterangan = trim($row[11] ?? '');

        // Extract phone number from column 10 if it looks like a phone
        $no_hp = $this->_extract_phone($phone_or_ket);

        // If column 10 wasn't a phone, treat it as additional keterangan
        if ($no_hp === null && !empty($phone_or_ket)) {
            $keterangan = $keterangan ?: $phone_or_ket;
        }

        // Detect status from keterangan
        $status = $this->_detect_status($keterangan, $jumlah_deposito);

        // Skip row if no_seri is invalid (ID required)
        if ($no_seri <= 0) {
            $stats['errors'][] = "Row $row_num: NO.SERI tidak valid";
            return false;
        }

        // Calculate jatuh tempo if not provided
        if (empty($tgl_jatuh_tempo) && !empty($tgl_deposito)) {
            $tgl_jatuh_tempo = date('Y-m-d', strtotime("$tgl_deposito + $jangka_waktu months"));
        }

        // Step 1: Find or create anggota
        $anggota = $this->_find_anggota_by_name($nama);

        if ($anggota) {
            $anggota_id = $anggota->id;
            $stats['anggota_found']++;

            // Update phone if we found one and existing is empty
            if ($no_hp && (empty($anggota->no_hp) || $anggota->no_hp === '-')) {
                $this->db->where('id', $anggota_id)
                    ->update('anggota', ['no_hp' => $no_hp]);
            }
        } else {
            // Create new anggota
            $anggota_data = [
                'nama' => $nama,
                'alamat' => $alamat,
                'no_hp' => $no_hp ?: '-',
                'status' => $status == 1 ? 'Aktif' : 'Non-Aktif',
                'created_at' => date('Y-m-d H:i:s')
            ];

            $this->db->insert('anggota', $anggota_data);
            $anggota_id = $this->db->insert_id();
            $stats['anggota_created']++;
        }

        // Step 2: Find or create deposito
        $existing_deposito = $this->_find_deposito_by_no_seri($no_seri);

        $deposito_data = [
            'anggota_id' => $anggota_id,
            'no_rekening' => 'DEP-' . str_pad($no_seri, 4, '0', STR_PAD_LEFT),
            'jumlah_deposito' => $jumlah_deposito,
            'jangka_waktu' => $jangka_waktu,
            'persentase_bunga' => $persentase_bunga,
            'tgl_mulai' => $tgl_deposito ?: date('Y-m-d'),
            'tgl_jatuh_tempo' => $tgl_jatuh_tempo,
            'keterangan' => $keterangan,
            'status' => $status
        ];

        if ($existing_deposito) {
            // Update existing
            unset($deposito_data['anggota_id']); // Don't change owner
            $this->db->where('id', $existing_deposito->id)
                ->update('deposito', $deposito_data);
            $stats['deposito_updated']++;
        } else {
            // Insert new
            $deposito_data['no_seri'] = $no_seri;
            $this->db->insert('deposito', $deposito_data);
            $stats['deposito_inserted']++;
        }

        return true;
    }

    // ==================== HELPER FUNCTIONS ====================

    /**
     * Convert Excel Serial Date to PHP date string
     * 
     * Excel stores dates as days since 1899-12-30 (with leap year bug)
     * Formula: Unix Timestamp = (serial - 25569) * 86400
     * 
     * @param mixed $serial Excel serial date number
     * @return string|null Date in Y-m-d format or null
     */
    private function _excel_date_to_php($serial)
    {
        // Handle empty, null, dash, 0
        if ($serial === null || $serial === '' || $serial === '-' || $serial == 0) {
            return null;
        }

        // Handle Excel error values (#NUM!, #VALUE!, etc.)
        if (is_string($serial) && strpos($serial, '#') === 0) {
            return null;
        }

        // If it's already a date string, try to parse it
        if (is_string($serial) && !is_numeric($serial)) {
            // Check for invalid dates
            if (strpos($serial, '1900-') !== false || strpos($serial, '1899') !== false) {
                return null;
            }
            $timestamp = strtotime($serial);
            if ($timestamp && $timestamp > 0) {
                $year = (int) date('Y', $timestamp);
                if ($year >= 2000 && $year <= 2100) {
                    return date('Y-m-d', $timestamp);
                }
            }
            return null;
        }

        // Convert Excel serial date to Unix timestamp
        $serial = floatval($serial);

        // Validate - reasonable Excel dates are > 36526 (year 2000)
        if ($serial < 36526 || $serial > 73051) { // Between year 2000 and 2100
            return null;
        }

        // Excel uses 1899-12-30 as day 0 (with leap year bug)
        // Unix uses 1970-01-01 as day 0
        // Difference is 25569 days
        $unix_timestamp = intval(($serial - 25569) * 86400);

        // Use gmdate to avoid timezone shifts
        return gmdate('Y-m-d', $unix_timestamp);
    }

    /**
     * Parse integer from Excel float value (e.g., 1.0 -> 1)
     * 
     * @param mixed $value Value to parse
     * @return int|null Integer or null for invalid values
     */
    private function _parse_int($value)
    {
        if ($value === null || $value === '' || $value === '-') {
            return null;
        }

        // Handle Excel errors
        if (is_string($value) && strpos($value, '#') === 0) {
            return null;
        }

        // Cast float to int (removes .0)
        if (is_numeric($value)) {
            return intval(floatval($value));
        }

        return null;
    }

    /**
     * Parse amount/currency value
     * Handles #NUM!, empty, dash, and currency formatting
     * 
     * @param mixed $value Value to parse
     * @return float Parsed amount (0 for invalid)
     */
    private function _parse_amount($value)
    {
        if ($value === null || $value === '' || $value === '-' || $value == 0) {
            return 0.0;
        }

        if (is_string($value) && strpos($value, '#') === 0) {
            return 0.0;
        }

        if (is_numeric($value)) {
            return floatval($value);
        }

        $value = (string) $value;
        $value = str_replace(['Rp.', 'rp.', 'Rp', 'rp', '$', ' ', 'Rs'], '', trim($value));

        $last_comma = strrpos($value, ',');
        $last_dot = strrpos($value, '.');

        if ($last_comma !== false && $last_dot !== false) {
            if ($last_comma > $last_dot) {
                $value = str_replace('.', '', $value);
                $value = str_replace(',', '.', $value);
            } else {
                $value = str_replace(',', '', $value);
            }
        } elseif ($last_comma !== false) {
            if (substr_count($value, ',') > 1) {
                $value = str_replace(',', '', $value);
            } else {
                $parts = explode(',', $value);
                if (strlen($parts[1]) == 2) {
                    $value = str_replace(',', '.', $value);
                } else {
                    $value = str_replace(',', '', $value);
                }
            }
        } elseif ($last_dot !== false) {
            if (substr_count($value, '.') > 1) {
                $value = str_replace('.', '', $value);
            } else {
                $parts = explode('.', $value);
                if (strlen($parts[1]) == 3) {
                    $value = str_replace('.', '', $value);
                }
            }
        }

        if (is_numeric($value)) {
            return floatval($value);
        }

        return 0.0;
    }

    /**
     * Parse interest rate from Excel
     * Handles formats: 0.006 (0.6%), 0.60%, 0.6
     * Returns rate as stored (e.g., 0.6 for 0.6% per month)
     * 
     * @param mixed $value Value to parse
     * @return float Parsed rate
     */
    private function _parse_rate($value)
    {
        if ($value === null || $value === '' || $value === '-') {
            return 0.6; // Default
        }

        // Handle Excel errors
        if (is_string($value) && strpos($value, '#') === 0) {
            return 0.6;
        }

        // Remove % sign
        $cleaned = str_replace(['%', ' '], '', (string) $value);
        $rate = floatval($cleaned);

        // Normalize: if very small (0.006), multiply by 100
        if ($rate > 0 && $rate < 0.1) {
            $rate = $rate * 100;
        }

        // If too large (60), divide by 100
        if ($rate > 10) {
            $rate = $rate / 100;
        }

        // Validate bounds
        if ($rate <= 0 || $rate > 5) {
            return 0.6;
        }

        return $rate;
    }

    /**
     * Extract phone number from value
     * Returns phone if starts with 08 or 62, otherwise null
     * 
     * @param string $value Value to check
     * @return string|null Sanitized phone or null
     */
    private function _extract_phone($value)
    {
        if (empty($value)) {
            return null;
        }

        // Remove spaces, dashes, parentheses
        $cleaned = preg_replace('/[\s\-\(\)]+/', '', $value);

        // Check if starts with 08 or 62
        if (preg_match('/^(08|62)\d{8,12}$/', $cleaned)) {
            return $cleaned;
        }

        return null;
    }

    /**
     * Detect deposit status from keterangan
     * 
     * @param string $keterangan Keterangan text
     * @param float $jumlah Amount
     * @return int 1=Aktif, 0=Non-Aktif
     */
    private function _detect_status($keterangan, $jumlah)
    {
        // If no amount, inactive
        if ($jumlah <= 0) {
            return 0;
        }

        // If no keterangan and has amount, active
        if (empty($keterangan)) {
            return 1;
        }

        $ket_lower = strtolower($keterangan);

        // Check for inactive patterns
        $inactive_patterns = [
            'lunas',
            'tarik',
            'cabut',
            'ditarik',
            'pokok ditarik',
            'pokok sudah ditarik',
            'pinalti'
        ];

        foreach ($inactive_patterns as $pattern) {
            if (strpos($ket_lower, $pattern) !== false) {
                return 0;
            }
        }

        return 1;
    }

    /**
     * Find anggota by name (case-insensitive)
     */
    private function _find_anggota_by_name($nama)
    {
        return $this->db->where('LOWER(nama)', strtolower(trim($nama)))
            ->get('anggota')
            ->row();
    }

    /**
     * Find deposito by no_seri
     */
    private function _find_deposito_by_no_seri($no_seri)
    {
        return $this->db->where('no_seri', $no_seri)
            ->get('deposito')
            ->row();
    }
}
